### ISSUE TITLE
[Server] feature / main addNote 기능 구현

### ISSUE THREAD

**Issue by icy9377** [codestates/Todaying-server#19]
### TODO
1. [ ] Job1  노트 추가를 위한Post 컨트롤러 작성
2. [ ] Job2 DB에 노트 데이터 싱크 확인
3. [ ] Job3  Get 요청을 통해서 원하는 데이터가 추후 조회가 되는지 확인
